TrialID = "covid19_confirmed_global-0-0"
EveryXSample = 1
IgnoreFirstDimension = false
DimRed = "PCA"
UseSubsampling = false
SubsamplingCount = 5
SubsamplingCountFixed = true
SubsamplingType = "catmullRom"
UseSubsamplesForEmbedding = false

[PCA]
random_state = 42
