TrialID = "covid19_confirmed_global-1"
EveryXSample = 1
IgnoreFirstDimension = false
DimRed = "PCA"
Dims = 50
OrigDims = 2023
Preprocessing = "standardization"

[PCA]
n_components = 50
random_state = 42
